### ISSUE TITLE
copy.txt contains assemblies that prevent ExampleMod from building if included

### ISSUE THREAD

**Issue by FelixBardner** [jixxed/StationeersMods#16]
I was following this repo's [documentation for making unity mods](https://github.com/jixxed/StationeersMods/blob/main/doc/CREATE-MOD-UNITY.md), and ran into errors like
`Plugin 'Assets/Assemblies/UnityEngine.UI.dll' has the same filename as Assembly Definition File 'Packages/com.unity.ugui/Runtime/UnityEngine.UI.asmdef'. Rename the assemblies to avoid hard to diagnose issues and crashes.`
and
`Library/PackageCache/com.unity.timeline@1.5.6/Editor/State/WindowState.cs(1013,41): error CS1061: 'Animator' does not contain a definition for 'UnbindAllHandles' and no accessible extension method 'UnbindAllHandles' accepting a first argument of type 'Animator' could be found (are you missing a using directive or an assembly reference?)`
that prevent the examplemod from building. The fix suggested to me was to remove any assemblies with "UnityEngine" in the name, and doing this let the project build and run correctly.
If these files really aren't needed, removing them from ExampleMod\Assets\Assemblies\copy.txt might be a good change.

**Comment by jixxed** [comment]
these have now been removed, though they don't block building the project. copy.txt needs to be updated from time to time with changes in the libraries from the game.
