### ISSUE TITLE
Having this mod installed, with all subscribed mods disabled, causes an error when using T-ray sensor lenses for pipes.

### ISSUE THREAD

**Issue by osolodo** [jixxed/StationeersMods#20]
I've tried to narrow down the cause of this issue as much as I can so here's what I've tried to isolate it.

System Specs:
- Processor: AMD Ryzen 5 3600 6-Core
- 32GB Ram
- Windows 11 Home 23H2

Reproduction Steps:
- Using a fresh install of BepInEx (Of the version specified in the readme, I've tried both and had the same results but for clarity assume 5.4.21)
- Using a fresh install of StationeersMods
- With all subscribed mods from the workshop disabled (I'm willing to unsubscribe if someone says it's a necessary debug step, but I'd rather not go there yet)
- In a new Creative world
- Spawn in the sensor lenses, the T-ray scanner & some pipes
- Place any pipe element
- Turn on the sensor lenses

[EXCEPTION] missingmethodexception: method not found: single assets.scripts.atmospherics.atmosphere.get_pressuregasses()

My observation is that I can use the T-ray scanner without causing this exception if either I remove StationeersMods from the BepInEx plugin folder or have no pipes in the game world.

I'm not sure where do find more detailed logs, or even what file this error is saved in since I pulled it from the on-screen output.
If someone could help me apply more detailed debug steps I would be very appreciative.

**Comment by jixxed** [comment]
issue with mod, contact mod developer
