### ISSUE TITLE
Pterodactyl / Linux issue - run_bepinex.sh fails

### ISSUE THREAD

**Issue by Sakata-MC** [jixxed/StationeersMods#6]
I had to modify the launch shell to 
#!/usr/bin/env bash

[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/container/Steam/logs/stderr.txt'
Logging directory: '/home/container/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1696019544
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '600760' already up to date.
:/home/container$ stty cols 80 rows 24; ./run_bepinex.sh ./rocketstation_DedicatedServer.x86_64
/home/container/rocketstation_DedicatedServer.x86_64
./run_bepinex.sh: line 117: file: command not found
Cannot identify executable type (got )!
Please create an issue at https://github.com/BepInEx/BepInEx/issues.

**Comment by QuintenQVD0** [comment]
> I had to modify the launch shell to #!/usr/bin/env bash
> 
> [Pterodactyl Daemon]: Finished pulling Docker container image steam user is not set. Using anonymous user. WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work. Redirecting stderr to '/home/container/Steam/logs/stderr.txt' Logging directory: '/home/container/Steam/logs' [ 0%] Checking for available updates... [----] Verifying installation... Steam Console Client (c) Valve Corporation - version 1696019544 -- type 'quit' to exit -- Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory OK Connecting anonymously to Steam Public...OK Waiting for client config...OK Waiting for user info...OK Success! App '600760' already up to date. :/home/container$ stty cols 80 rows 24; ./run_bepinex.sh ./rocketstation_DedicatedServer.x86_64 /home/container/rocketstation_DedicatedServer.x86_64 ./run_bepinex.sh: line 117: file: command not found Cannot identify executable type (got )! Please create an issue at https://github.com/BepInEx/BepInEx/issues.



this is pterodactyl, and the file command is not installed in any of our docker images.
